name: todo_gamified
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.3
  uuid: ^4.5.1
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7  # Hinzugefügt für die Bildauswahl
  path_provider: ^2.1.2  # Hinzugefügt für Dateipfad-Operationen
  cached_network_image: ^3.3.1  # Hinzugefügt für effizientes Laden und Caching von Netzwerkbildern


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true
  generate: true